### ISSUE TITLE
geom_tippoint doesnt work in combination with ggplot() + geom_ret()

### ISSUE THREAD

**Issue by arthurKocher** [grdspcht/ggarg#13]
The error message says it misses the x and y aes, so probably affecting other functions. It works with ggret so maybe one could just stick to using this but then maybe remove geom_ret from the package?

Test code:

```
retnet = read.enewick("../data/retnet.nwk")
ggret(retnet) + geom_tippoint() #works
ggplot(retnet) + geom_ret() + geom_tippoint() #doesn't work
```

**Comment by grdspcht** [comment]
This is quite curious

If we follow your example above, geom_tippoint() indeed does not work right out of the box.
This can be circumvented by specifying the aesthetic values of the x and y coordinates like this:
```R
ggplot(retnet, aes(x,y)) + geom_ret() + geom_tippoint() # works
```
or like this 
```R
ggplot(retnet) + geom_ret() + geom_tippoint(aes(x,y)) # works
```

Interestingly though, other similar geoms such as geom_tiplab() still work without specifically defining aes()
```R
ggplot(retnet) + geom_ret() + geom_tiplab() # works

ggplot(retnet) + geom_ret() + geom_tiplab()  + geom_tippoint() # doesn't work
```

I am not completely sure what causes this and will have a look at the ggtree code for these geom. There must be some difference in how thy inherit the required aesthetic mappings (x, y-values here)

In another interesting case this seems to hold true for regular ggtree objects too

```R
primates <- read.newick("~/Downloads/primates.newick") # I use primates.nwk from icytree for testing purposes but feel free to try any other newick tree

ggplot(primates) + geom_tree() + geom_tippoint() # does not work. Same error. 

# This however works again
ggtree(primates) + geom_tippoint()

I will have to do some more research

**Comment by arthurKocher** [comment]
seems rather related to ggtree
