### ISSUE TITLE
geom_arg options

### ISSUE THREAD

**Issue by arthurKocher** [grdspcht/ggarg#4]
- layout option doesn't work (remove it?)
- retcol option doesn't work, this should be solved
- arrowheads obtained with the arrow=T options have a weird aspect (this not so important though..)
- rettype option doesn't work (remove it?)

Example code:
```
retnet = read.enewick2("retnet.nwk")
ggtree(retnet) + theme_tree() + geom_arg()
ggtree(retnet) + theme_tree() + geom_arg(layout = "slanted") #doesn't work
ggtree(retnet) + theme_tree() + geom_arg(retcol = 'blue') #doesn't work
ggtree(retnet) + theme_tree() + geom_arg(arrows = T) # arrowheads have a weird aspect
ggtree(retnet) + theme_tree() + geom_arg(retlinetype = 3)
ggtree(retnet) + theme_tree() + geom_arg(rettype = 'snake') #doesn't work
```

**Comment by grdspcht** [comment]
Removed layout options for now and fixed the retcol issue.
https://github.com/grdspcht/ggarg/commit/6120002dcd8b3092a75312a42abefe707d609744

Can't replicate the problem with rettype argument, using` rettype = "snake"` or `"straight"` works as intended for me
